# Generated by Django 5.2.4 on 2025-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_desk_options_alter_library_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={},
        ),
        migrations.AlterField(
            model_name='library',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
