# Generated by Django 5.2.4 on 2025-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_desk_qr_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'ordering': ['-created_at'], 'verbose_name': 'Desk', 'verbose_name_plural': 'Desks'},
        ),
    ]
