# Generated by Django 5.2.4 on 2025-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_desk_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={},
        ),
        migrations.AlterField(
            model_name='desk',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
