# Generated by Django 5.2.4 on 2025-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_desk_options_alter_desk_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
