# Generated by Django 5.2.4 on 2025-07-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_desk_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': 'Desk', 'verbose_name_plural': 'Desks'},
        ),
        migrations.RemoveField(
            model_name='desk',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='qr_sent',
        ),
    ]
