# Generated by Django 5.2.4 on 2025-07-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_desk_options_remove_desk_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
    ]
