# Generated by Django 5.2.4 on 2025-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_desk_options_alter_library_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
