# Generated by Django 5.2.4 on 2025-07-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='core.user')),
            ],
            options={
                'unique_together': {('user', 'desk')},
            },
        ),
    ]
