# Generated by Django 5.2.4 on 2025-07-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDesk',
        ),
    ]
