# Generated by Django 5.2.4 on 2025-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.IntegerField(),
        ),
    ]
