# Generated by Django 5.2.4 on 2025-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_desk_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='library',
        ),
        migrations.AddField(
            model_name='library',
            name='desks_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Desk',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
