# Generated by Django 5.2.4 on 2025-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_library_library_desks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='core.user'),
        ),
    ]
