# Generated by Django 5.2.4 on 2025-07-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_category_user_current_state_cart_cartitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
